---
name: idr0135-hodis-melanocytes/experimentA
version: 1

defaults:
  include: false
  type: string
  split:
  includeclient: true
  visible: true
  omitempty: true

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: true

  - name: Material Type
    clientname: Material Type
    include: true

  - name: Experimental Condition [Cell Type]
    clientname: Cell Type
    include: true

  - name: Comment [Cell Type Comments]
    clientname: Cell Type Comments
    include: true

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: true

  - name: Experimental Condition [ID]
    clientname: ID
    include: true

  - name: Experimental Condition [Batch]
    clientname: Batch
    include: true


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism 1]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism 2]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 1]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 1]
          clientname: Gene Identifier URL
          clientvalue: >
                http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 1]
          clientname: Gene Symbol
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 2]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 2]
          clientname: Gene Identifier URL
          clientvalue: >
              http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 2]
          clientname: Gene Symbol
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 3]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 3]
          clientname: Gene Identifier URL
          clientvalue: >
              http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 3]
          clientname: Gene Symbol
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 4]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 4]
          clientname: Gene Identifier URL
          clientvalue: >
             http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 4]
          clientname: Gene Symbol
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 5]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 5]
          clientname: Gene Identifier URL
          clientvalue: >
              http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 5]
          clientname: Gene Symbol
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene/supplementary
      columns:
      - name: Comment [Gene Annotation Comments]
        clientname: Gene Annotation Comments
        include: true


advanced:
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol

